# Redis Production Setup for Atlas Platform Performance Caching
version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: atlas-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-atlas_redis_pass_2024}
    command: >
      redis-server 
      --requirepass ${REDIS_PASSWORD:-atlas_redis_pass_2024}
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
      --appendonly yes
      --appendfsync everysec
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - atlas-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: atlas-redis-ui
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379:0:${REDIS_PASSWORD:-atlas_redis_pass_2024}
      - HTTP_USER=admin
      - HTTP_PASSWORD=${REDIS_UI_PASSWORD:-redis_admin_2024}
    networks:
      - atlas-network
    depends_on:
      - redis
    profiles:
      - monitoring

volumes:
  redis_data:
    driver: local

networks:
  atlas-network:
    external: true