services:
  - type: web
    name: atlas-platform
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: atlas-db
          property: connectionString
    autoDeploy: true

databases:
  - name: atlas-db
    databaseName: atlas_production
    user: atlas_user
    plan: free